version: '3.7'

services:
  flaskapp:
    build: .
    container_name: flaskapp
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
